### ISSUE TITLE
datacenterAvailability: EACH might be broken with useAddressTranslator: true

### ISSUE THREAD

**Issue by maikzumstrull** [thelastpickle/cassandra-reaper#1028]
I have inherited a cluster and am trying to get Reaper 2.2.1 working, and it seems to be completely unable to start any repairs. Depending on how it's started, either the repair job never appears as running, or every segment is stuck in NOT_STARTED forever.

According to the log, segments keep getting postponed because metrics are unavailable. Also according to the logs, it keeps trying (and failing) to connect to JMX endpoints that are in other datacenters, which doesn't work. I think it shouldn't attempt to do that with `datacenterAvailability: EACH`, but maybe `useAddressTranslator: true` is confusing the reachability check?

Starting a new repair job (that isn't already existing and in running state) also fails with a JMX error, from trying to connect to a node it shouldn't connect to.

It's entirely possible I'm using it wrong, I have no previous experience with the reaper, but I feel like I've checked all the obvious things and at this point it seems like a bug.

**Comment by adejanovski** [comment]
Hi @maikzumstrull,

`EACH` mode is definitely broken in 2.2, you're not doing anything wrong.
I'm working on a patch that I can hopefully release soon.
In the meantime, you have two options:

- Use `LOCAL` instead of `EACH` which will allow you to run repairs with lower backpressure guarantees on checking pending compactions (each Reaper instance will not be able to get the pending compactions from the other datacenter), but repairs will still be global to the cluster
- Downgrade to 2.1.3

**Comment by maikzumstrull** [comment]
Thanks for the update, I'll give `LOCAL` a try and watch for new releases.

**Comment by jsanda** [comment]
@adejanovski can we close this since #1029 has been merged?

**Comment by maikzumstrull** [comment]
For me, it's fixed with the new release. Go ahead unless you're tracking something else here.

**Comment by jdonenine** [comment]
As discussed, this was resolved.
