### ISSUE TITLE
List of repairs running doesn't show the number of running repairs

### ISSUE THREAD

**Issue by afsanchez83** [thelastpickle/cassandra-reaper#1080]
**Spotted on 2.2.4 (b399882)**

Hi!,

When I'm in the Repairs section by default the Display is 10 but it's just showing 4 repairs running, see example below:
![image](https://user-images.githubusercontent.com/79571496/119463590-e9d2d680-bd0f-11eb-8d8a-986f1c3a84e8.png)

Although, when I change this value to 25 I can see all the repairs running:

![image](https://user-images.githubusercontent.com/79571496/119463916-3ae2ca80-bd10-11eb-8d12-6c42740464d8.png)

Is that expected behavior or is it a malfunction of the repair section?

Thanks in advance.

**Comment by adejanovski** [comment]
This is expected indeed (although it can be puzzling as a behavior).
The running and finished repair runs are listed in a single query which applies the limit clause, and only after are they separated into RUNNING/PAUSED and DONE states to fill both tables.
If you have a lot of PAUSED runs, then you'll have DONE runs which are more recent than the PAUSED ones, which will put the PAUSED ones out of the limit threshold.
Maybe the default threshold should be higher to limit the odds of this happening..?

**Comment by afsanchez83** [comment]
Thanks for the answer, 

I understand, I would divide Running repairs from Done repairs because the most of the time I want to check them separately and you will avoid this kind of behaviors, however that you proposed al least help to mitigate this kind of issues.

**Comment by a-nldisr** [comment]
@adejanovski Sorry, but it seems a bit broken and unexpected. 
So what happens when we have more than 100 repairs? Since 100 is the maximum in the drop down menu?
I ran into this issue because I had 10 finished repairs, 3 running repairs however were no longer listed. So if i have a list of 100 completed tasks, I will have to delete them before I can see the running repairs?

Would it be an idea to setup Pagination?

**Comment by adejanovski** [comment]
This was fixed in v3.3.0
