### ISSUE TITLE
Cassandra reaper 3.1.0 --> is faulty, replica set changed since repair was started: io.cassandrareaper.core.

### ISSUE THREAD

**Issue by aby786** [thelastpickle/cassandra-reaper#1161]
we deployed Cassandra reaper 3.1.0 and "system" and "system_schema" keyspace are failing with no specific errors but below warning message.
FYI: this completes successfully on another cluster   with same settings but only difference is reaper 1.2.2 [ success] and another cluster 3.1.0[failing] 

Also 3.1.0 completes on rest of keyspaces successfully like user and others, so anything changed in Cassandra reaper 3.1.0 ?

------------------------------------------------------------------------------------------------------------------------------------------------
INFO   [2022-01-26 12:39:27,293] [dit1cascluster:cab205b0-7ece-11ec-bd3b-7bbc29f5c10b:cab253d1-7ece-11ec-bd3b-7bbc29f5c10b] i.c.s.SegmentRunner - Nothing to repair for segment cab253d1-7ece-11ec-bd3b-7bbc29f5c10b in keyspace system_schema
INFO   [2022-01-26 12:39:37,277] [dit1cascluster:cab205b0-7ece-11ec-bd3b-7bbc29f5c10b] i.c.s.RepairRunner - Attempting to run new segment...
INFO   [2022-01-26 12:39:37,291] [dit1cascluster:cab205b0-7ece-11ec-bd3b-7bbc29f5c10b] i.c.s.RepairRunner - Next segment to run : cab205b2-7ece-11ec-bd3b-7bbc29f5c10b
WARN   [2022-01-26 12:39:37,303] [dit1cascluster:cab205b0-7ece-11ec-bd3b-7bbc29f5c10b] i.c.s.RepairRunner - Segment #cab205b2-7ece-11ec-bd3b-7bbc29f5c10b is faulty, replica set changed since repair was started: io.cassandrareaper.core.Segment@4c704168
INFO   [2022-01-26 12:39:37,317] [dit1cascluster:cab205b0-7ece-11ec-bd3b-7bbc29f5c10b] i.c.s.RepairRunner - Repair amount done 6.0
------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by adejanovski** [comment]
Hi @aby786,

You should not attempt to repair `system` nor `system_schema`. These are non replicated keyspaces whose data are specific to each node.
That's why it's telling you there's nothing to repair in 1.2.2.
A lot changed indeed between 1.2.2 and 3.1.0, including a comparison of then set of replicas when the repair was created and the moment a segment starts. Since you have no replication on those 2 keyspaces, the repairs exit with an error.
If you've created schedules for these two keyspaces, you should delete them and everything should be fine.

**Comment by aby786** [comment]
Thanks @adejanovski  !
