### ISSUE TITLE
Unable to delete aborted repair...

### ISSUE THREAD

**Issue by pmeisen** [thelastpickle/cassandra-reaper#1172]
... the repair is aborted and shown as such in the UI, see 
![Screen Shot 2022-03-11 at 5 12 21 PM](https://user-images.githubusercontent.com/2893215/157997598-073bd4b3-1378-4b79-9763-0845451e0723.png)

but it cannot be deleted, since it complains that the repair is still running. Looking at the segments, one of the segments is marked as still running:
![Screen Shot 2022-03-11 at 5 13 34 PM](https://user-images.githubusercontent.com/2893215/157997600-6cef54c1-b3ba-4dc0-9395-ba67d70014fc.png)

This segment cannot be aborted, since the system complains that the repair is aborted.

How can we clean this up?

Thanks!

**Comment by adejanovski** [comment]
Hi @pmeisen,

could you try restarting Reaper? It should update the segment state shortly after restart and then allow deleting the repair.

**Comment by Rooks103** [comment]
My suggestion would be use the `GET /repair_run` API call and look for anything in the state of `RUNNING`. That should give an ID for the repair, and you can issue a `PUT /repair_run/<ID>/state/PAUSED` followed by a `DELETE /repair_run/<ID>?owner=<Owner>`. 

I had something similar where the clusters page showed a repair, but the repairs page wasn't showing it. The above procedure was how I got the UI clean again.

**Comment by adejanovski** [comment]
I'll close this ticket as it's been inactive for a while.
Feel free to reopen if you're still experiencing this issue.

**Comment by mortenjoenby** [comment]
@adejanovski, is it correct that this was never fixed?
I have exactly this issue - on version 2.3.0 (!) - but assuming it hasn't been fixed, this issue will also be in later versions.
I have aborted the repair, but one segment is still active, so occupying 1 of the 2 allowed parallel repairs. I can't restart Reaper right now as my experience unfortunately is that other running repairs might fail. And I have a large repair running that takes several days. I don't want to risk having to restart it.
This issue is for sure a problem that should be solved.

**Comment by mortenjoenby** [comment]
Trying to abort segment won't work on an aborted repair:

```
spreaper abort-segment 00000000-0000-000b-0000-000000000000 00000000-0000-02a8-0000-000000000000
# Aborting a segment with run id: 00000000-0000-000b-0000-000000000000 and segment id 00000000-0000-02a8-0000-000000000000
Cannot abort segment on repair run with status ABORTED
```

**Comment by mortenjoenby** [comment]
@Rooks103 ,
> My suggestion would be use the `GET /repair_run` API call and look for anything in the state of `RUNNING`. That should give an ID for the repair, and you can issue a `PUT /repair_run/<ID>/state/PAUSED` followed by a `DELETE /repair_run/<ID>?owner=<Owner>`.
> 
> I had something similar where the clusters page showed a repair, but the repairs page wasn't showing it. The above procedure was how I got the UI clean again.

I have seen the same thing. The reason for the repair not showing up in the "Repairs" page is (at least in our case) that the UI has an annoying limitation of only being able to show up to the last 100 repairs. So if the given repair is older than those 100 it's simply not shown! The UI should be fixed.
My solution to that is simply to manually delete entries until it shows up!

**Comment by dpavlov-smartling** [comment]
Hello @Rooks103 ,
Got the same issue on version 4.0.0-beta4 which runs on Cassandra4 and uses it as a backend.
Restarted reaper and this didn't help.
Fixed using the following steps:
1. Manually stopped running Cassandra repair via `nodetool repair_admin`
2. Set segment_status to 0 for the segment in question directly in reaper_db keyspace:
```
update reaper_db.repair_run set segment_state=0 where id=REPAIR_ID and segment_id=SEGMENT_ID;
```

I think this issue should be re-opened, because it still persists and restarting the reaper doesn't help.

NB: I did restart reaper and wait an hour after manually stopped the repair on Cassandra cluster. Was hoping that Reaper will sync its backend automatically, but that didn't happen.
