### ISSUE TITLE
accessControl sessionTimeout cassandra-reaper

### ISSUE THREAD

**Issue by lgrandotto** [thelastpickle/cassandra-reaper#1225]
Hi,

OS :
CentOS Linux release 7.9.2009 (Core)

I certify that the config sessiontimout do not work in file cassandra-reaper.yaml

"accessControl:
  sessionTimeout: PT10M"

The session stay open after 10 minutes. I testing change to PT60S with the same results.

Otherwise all work correctly but no the sessiontimout.

Somebody do have a idea please ? A bug may be ?

Best regards.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1790) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1790
┆priority: Medium

**Comment by ossarga** [comment]
I’ve run a test where I changed the sessionTimeout to PT1M (1 minute) and I changed the UI polling interval to 5 minutes (and recompiled Reaper). Under those conditions and when no cluster is added, the UI session does time out and the user is taken back to the login screen. However, as soon as a cluster is added, or sessionTimeout and UI polling interval are at their default values, the UI session never times out. This is because the UI is constantly polling the server.

**Comment by adejanovski** [comment]
> This is because the UI is constantly polling the server

Interesting, I never thought of that 😅

**Comment by lgrandotto** [comment]
Hi,

Thank for answer.

This fact may be correct the next version ?

Best regards.

**Comment by ossarga** [comment]
Hi @lgrandotto, it is hard to say which version this will be fixed in. I will be in active discussions with @adejanovski about the issue, as there is another user that requires this to be fixed. So there should be a patch for this fairly soon.
