### ISSUE TITLE
Executing SegmentRunner failed: ReadableInstant objects must not be null

### ISSUE THREAD

**Issue by benthorner** [thelastpickle/cassandra-reaper#132]
We're getting periodic errors like this when running repairs:

    ERROR [2017-07-04 09:28:11,482] com.spotify.reaper.service.RepairRunner: Executing SegmentRunner failed: ReadableInstant objects must not be null

Looking through the code, I think it might be SegmentRunner:236, which is using a Joda between method. Repairs do seem to be working, so not sure if this is a bug or something weird about our cluster. Really useful program, by the way :-)

**Comment by adejanovski** [comment]
Hi @benthorner,

the error suggests that either the start date or the end date is null, which is clearly unexpected and points to the segment being updated (postponed) by another thread than the one processing it.
Since the only place this is called is a debug logging, I've just pushed a fix by removing this call.

A "real" fix is coming from the upcoming FT branch (ft-reaper-improvements-final) where @michaelsembwever added a lot of checks to disallow this kind of unexpected update on the segments.

Happy you like reaper :)
