### ISSUE TITLE
Does a reaper repair cycle have to complete before gc_grace_seconds passes? 

### ISSUE THREAD

**Issue by Ritu-Thakur** [thelastpickle/cassandra-reaper#160]
If it doesn't, how would repair be affected?

**Comment by rustyrazorblade** [comment]
A given tombstone must be repaired before gc_grace_seconds passes if that tombstone was not correctly replicated to every node that owned the partition that was affected.  If the tombstone is not replicated before gc_grace_seconds, it's possible the tombstone will be removed from the other replicas, and the original data will be resurrected on the replica which didn't have the tombstone.  The original data might then be replicated back to the nodes which cleared the tombstone out due to gc_grace_seconds passing.

**Comment by rustyrazorblade** [comment]
For future reference, this is a question better fit for the mailing list:

https://groups.google.com/forum/#!forum/tlp-apache-cassandra-reaper-users
