### ISSUE TITLE
discuss moving segment count to a field under an "advanced" dropdown and having reaper compute it

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#161]
We should be able to compute this rather than require the user to input it.

**Comment by michaelsembwever** [comment]
the variable here is that it depends on partition sizes. if you have some very big partition sizes you can increase the segment count, which reduces the segment range, and have more chance of getting troublesome segments repaired.

it's a cumbersome, and not always appropriate, approach to deal with big partitions.

an idea around this is that we could automatically split segments when they fail (eg twice consecutively).
and in the worse case repairs would then at least repair every partition except those causing failures. (whether this is actually feasible i'm not sure. how many segment fails would this entail and how long would that repair end up taking?)

**Comment by elsmorian** [comment]
Just my two pence as a Reaper user, its handy to be able to change segment counts through the UI. What might be a quick solution is just suggesting a count pre-filled in the UI but allow people to override if they wish?

(The automatic splitting of segments that fail sounds good, but I feel it should also learn if many segments of a certain size are failing and having to be split - it should start using the new smaller size for all next segments maybe?)

**Comment by rustyrazorblade** [comment]
I've put a little more thought into this, and you're right @elsmorian , there's valid use cases for it.  Maybe hiding it under an "Advanced options" area might be useful.  

Almost everyone I've ever tried to help set up reaper has found the segment count to be incredibly confusing.

**Comment by adejanovski** [comment]
There is actually no requirement to set the segment count in order to run repairs. Reaper will use the max(default_number_of_segments, number_of_vnodes) if the value is not set.

I'd prefer people knowing that this exist as understanding segments is essential to understand how Reaper performs repairs. 
The suggestion of @michaelsembwever about splitting failing segments automatically is interesting (needs some good thinking though), and we might want to display the computed value by default instead of letting the field empty. 

I'm -1 on hiding this under "Advanced options".

**Comment by rustyrazorblade** [comment]
If there's no requirement for segment count, we should make it obvious in the UI that it can be left blank.

**Comment by michaelsembwever** [comment]
The UI concept of "segment count" could be simplified a lot, making life a lot easier for both user and developers.

For example, why not make it "segments per vnode" with the default value 1.
I'd find that a lot more intuitive to use, that is increase it to 2 or 3 (or more) for really big repairs/partitions. 
I suspect this would simplify a lot of the code as well…?

**Comment by rustyrazorblade** [comment]
My biggest gripe with the segment count is that unless you know the code, it adds a lot of confusion.  I like the idea of it being per node or per vnode, as then segment count doesn't have to change as you add nodes to the cluster, which is a nicer user experience.

**Comment by rustyrazorblade** [comment]
My understanding is the bottommost leaves of the tree (assuming the whole tree was kept in tact) were hashes of entire partitions, not individual cells, meaning partition size wouldn't matter.  Looking at org/apache/cassandra/utils/MerkleTree.java, I'm seeing this:

```
      /**
     * Hash value representing a row, to be used to pass hashes to the MerkleTree.
     * The byte[] hash value should contain a digest of the key and value of the row
     * created using a very strong hash function.
     */
    public static class RowHash
    {
        public final Token token;
        public final byte[] hash;
        public final long size;
        public RowHash(Token token, byte[] hash, long size)
        {
            this.token = token;
            this.hash  = hash;
            this.size = size;
        }

        @Override
        public String toString()
        {
            return "#<RowHash " + token + " " + Hashable.toString(hash) + " @ " + size + " bytes>";
        }
    }
```

Row here seems to be using the old terminology (note the reference to Token).  I checked where the object is created, found `org/apache/cassandra/repair/Validator.java`, where it's using the UnfilteredRowIterator, which iterates over the rows of a partition:

```
    private MerkleTree.RowHash rowHash(UnfilteredRowIterator partition)
    {
        validated++;
        // MerkleTree uses XOR internally, so we want lots of output bits here
        CountingDigest digest = new CountingDigest(FBUtilities.newMessageDigest("SHA-256"));
        UnfilteredRowIterators.digest(null, partition, digest, MessagingService.current_version);
        // only return new hash for merkle tree in case digest was updated - see CASSANDRA-8979
        return digest.count > 0
             ? new MerkleTree.RowHash(partition.partitionKey().getToken(), digest.digest(), digest.count)
             : null;
    }
```

Besides, the tree is a fixed height, meaning the courser hashes are at the top, so again I don't think partition sizes would matter, but the number of keys would.  

Lastly I'd like to think that if we're here discussing the nuance of how this stuff works it's way to complicated for the overwhelming majority of reaper users and they shouldn't even be bothered to see it.

**Comment by adejanovski** [comment]
So, the current way of taking the segment count as input is either confusing or does not scale with the cluster (add nodes and you'll need to change the segment count of the job).

I guess we could hide the parameter and try to compute it ourselves. The rule could be something like (values must be precisely determined) : 

- if there are more than 32 vnodes per node, use the number of vnodes as segment count (we probably don't want to split the job more than that)
- if there are less than 32 vnodes, we could compute the number of segments based on node density (that could take some experiments to get it right)
- Users can override the value anytime, giving their own "segments per vnode" value (instead of a global segment count)

This is kind of a breaking change though and we'll have to migrate existing schedules/jobs to that new way of computing the number of segments.

**Comment by marshallking** [comment]
As a new user to Cassandra-Reaper I have to agree .. the segments field in the UI is very confusing. And on top of that,  even if I add a value here Cassandra Reaper seems to ignore what ever I put into this field. I did look through the code a little bit and see that it is ignored if you have incremental repairs selected. What would be nice is if the "Segments"  field could be described/documented a little bit more. How is the segments number computed? When is is used/not used? Maybe some simple use cases... etc.

**Comment by adejanovski** [comment]
Segment count per node is part of 1.0.0-RC1.

Closing the ticket
