### ISSUE TITLE
Untangle project structure

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#163]

**Comment by michaelsembwever** [comment]
i've been eyeing this off. i've no opinion on using `.spotify.`, it is a compliment and recognition, but i see the need to clean up the packaging structure. there's class dependency tangles, some not very intuitive placement, and "layer" packages instead of "feature" packages.

http://www.javapractices.com/topic/TopicAction.do?Id=205

**Comment by michaelsembwever** [comment]
The following diagram (from structure101) shows that the whole project is tangled but ReaperException and utils. (and utils is a layer package we don't want)

<img width="418" alt="screen shot 2017-08-26 at 09 58 55" src="https://user-images.githubusercontent.com/559444/29736551-969b69b0-8a45-11e7-8cc7-2ffca7da729b.png">

**Comment by michaelsembwever** [comment]
This is the diagram from the code when it was at spotify…
<img width="596" alt="screen shot 2017-08-27 at 11 07 13" src="https://user-images.githubusercontent.com/559444/29746276-4295c99a-8b18-11e7-97b5-24f14226a0f9.png">

(you can see that it's basically the same, the `ft-reaper-improvements-final` branch did though introduce extra tangles. tangles, or circular dependencies are represented by the red arrows.)

**Comment by michaelsembwever** [comment]
I took a quick [experiment](https://github.com/thelastpickle/cassandra-reaper/tree/mck/refactor-packages-by-feature-0) at refactoring to package-by-feature, so that packages look like:

<img width="315" alt="screen shot 2017-08-27 at 10 53 48" src="https://user-images.githubusercontent.com/559444/29746302-c2bcda32-8b18-11e7-9df6-0c00e9a77a8e.png">

This gave the following tangles:

<img width="513" alt="screen shot 2017-08-27 at 10 51 57" src="https://user-images.githubusercontent.com/559444/29746334-d00d0f44-8b19-11e7-98c1-caf31eba54bc.png">

This starts to look better, but still shows that there's a far bit of untangling to do.
In the [refactor-packages-by-feature-0](https://github.com/thelastpickle/cassandra-reaper/tree/mck/refactor-packages-by-feature-0) branch the commit message is keeping a list of easy-wins to untangles.

**Comment by michaelsembwever** [comment]
> rustyrazorblade changed the title from switch packages structure to com.thelastpickle to Untangle project structure 2 hours ago

Thanks for the ticket rename. My apologies for hijacking the ticket.

> In the refactor-packages-by-feature-0 branch the commit message is keeping a list of easy-wins to untangles.

A number of these easy-wins have been applied in the following PRs:

 - https://github.com/thelastpickle/cassandra-reaper/pull/166
 - https://github.com/thelastpickle/cassandra-reaper/pull/167
 - https://github.com/thelastpickle/cassandra-reaper/pull/168
 - https://github.com/thelastpickle/cassandra-reaper/pull/169
 - https://github.com/thelastpickle/cassandra-reaper/pull/170
 - https://github.com/thelastpickle/cassandra-reaper/pull/171

This leaves the project in the following, slightly less tangled, state:

<img width="576" alt="screen shot 2017-08-29 at 07 09 32" src="https://user-images.githubusercontent.com/559444/29793974-674700ac-8c89-11e7-961a-3dc6c83a1cb5.png">

**Comment by adejanovski** [comment]
The project structure was untangled and has been stable for a while.
@michaelsembwever, I'll close the ticket for now. Let's open a new one if there's further work to be done.
