### ISSUE TITLE
Ability to repair a specific list of hosts

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#165]
Reaper doesn't currently allow to handle repair to recover from single nodes outages.
We should be able to specify the nodes we want to repair.

In the UI, node selection should be assisted (auto completion) and be using a tag input component like this one : https://www.npmjs.com/package/react-tag-input

**Comment by rustyrazorblade** [comment]
I'm a -1 on this feature until we know how it behaves in the real world.

Edit: Sorry, I misread the intent of this feature.  +1!

**Comment by michaelsembwever** [comment]
My gut feeling is that we should first tackle https://github.com/thelastpickle/cassandra-reaper/issues/161

Similar to the HA and localMode, i'm **curious** about how/if this issue can be broken up.
That's not just breaking it up by features, but breaking up the technical steps involved in this ticket.

I'd also be in favour of documenting a few use cases where this would be used. (Documenting use cases generally is going to be a win for us, and there seems to be already a far few different approaches on how to apply reaper.)
So that's a vote on seeing tests written with/before code, but to see (some of the) documentation written first too!

**Comment by adejanovski** [comment]
Done in master
