### ISSUE TITLE
travis testing

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#19]

**Comment by adejanovski** [comment]
@rustyrazorblade : I added a basic Travis yml file that builds reaper, runs the tests and runs a Sonar analysis on the code. Sonar sends feedback on the code directly in the pull requests.

I'm going to push the PR that has distinct integration tests running with a local ccm cluster, so that we can add a test run for each Cassandra version we support in Travis.

**Comment by adejanovski** [comment]
This is fully ready in PR #35
