### ISSUE TITLE
Allow more parallel repairs

### ISSUE THREAD

**Issue by mrwulf** [thelastpickle/cassandra-reaper#205]
Segment runner should be configurable to allow hosts to be repairing more than a single segment at a time. Specifically the check for `metrics.hasRepairRunning()` seems to be too restrictive.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-300) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-300

**Comment by hkroger** [comment]
👍

**Comment by adejanovski** [comment]
This is sadly not as simple as it may look.
The problem is that we cannot identify which segment is running on a node, we can only know that there is some repair in progress. Internally, Reaper will try to check if its view of segment statuses is up to date by checking if repairs are running on a node (with the certainty that there can be only one at a time). 
It then can take the decision to force terminate all repairs on nodes reporting a repair in progress while Reaper's database says none should be.
Which leads us to another limitation of Cassandra : we can only force terminate all running repairs, and not specific ones. It would be then impossible to kill a segment that has been running over the maximum allowed time, without cancelling other "valid" running segments.
We also abort segments in some cases when a repair run is paused, and soon when it's aborted, which would lead us to the same issue.

I see no way around this without a profound change to Reaper's core, which is currently unlikely to happen.

**Comment by hkroger** [comment]
Is this something that should be communicated to Cassandra project so they could offer better API towards the repairs?

**Comment by adejanovski** [comment]
This feature shipped in 3.0.
