### ISSUE TITLE
Remove ability to delete repair runs

### ISSUE THREAD

**Issue by michaelsembwever** [thelastpickle/cassandra-reaper#208]
Currently it's possible to delete repairs runs that are currently running.

While there's a superficial constraint that the repair run must be first be put in PAUSED state. Neither the PAUSED nor the ABORTED state stop/abort currently running repair segments. When these repair segments finish they add "zombie" rows in the repair run partition.¹

From the user's perspective the only difference between a DELETED and an ABORTED repair run is if the run at any point was running.

If deleting a repair run is possible then it should only be possible on a repair run with a NOT_STARTED state. And it can be done by either deleting the partition or by adding a DELETED state.

When aborting a repair run we should also abort all running repair segments.

- - -
¹) attempts to getRepairRun(..) fail were previously failing with zombie segments

```
! java.lang.NullPointerException: Name is null
! at java.lang.Enum.valueOf(Enum.java:236)
! at com.spotify.reaper.core.RepairRun$RunState.valueOf(RepairRun.java:156)
! at com.spotify.reaper.storage.CassandraStorage.buildRepairRunFromRow(CassandraStorage.java:911)
! at com.spotify.reaper.storage.CassandraStorage.getRepairRun(CassandraStorage.java:381)
! at com.spotify.reaper.resources.RepairRunResource.deleteRepairRun(RepairRunResource.java:601)
```

fyi adejanovski

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-302) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-302

**Comment by adejanovski** [comment]
I disagree on this one. We should be able to delete past runs.
I'm not a fan of evergrowing databases.

-1

**Comment by rustyrazorblade** [comment]
Every cassandra deployment is ever growing, how many rows are we actually talking about?

**Comment by adejanovski** [comment]
Over time it could be a lot.

Another way to handle this could be to set a TTL on the repair run table instead of having manual deletes. This way we would only keep the "last x days" of repair history. 
Then, different backends would not allow this to be handled the same way, but I'm in favor of auto deletion after some time.
Keeping an ever growing repair history is useless, will clutter the UI and make listing the repairs very long over time (we list all repairs to find the ones in RUNNING state every 30s).
We would then also need to remove the safety checks that prevent deleting a cluster if we still have repair runs in the table.

**Comment by rustyrazorblade** [comment]
I'm fine with a TTL on repair runs, but does that introduce any potential race conditions?  Like if we pause a repair, will it just disappear after a while?  Does that matter?

**Comment by adejanovski** [comment]
Since TTL won't work with other backends, we should better handle cleanups ourselves. 
This way we could make sure that repair is in an appropriate state to be deleted.

**Comment by michaelsembwever** [comment]
Addressing the concerns raised:

> Since TTL won't work with other backends, we should better handle cleanups ourselves.

**This ticket only applies to the C\* backend.**
It's the only backend that suffers from the problems described around zombie segments, because segments and runs are stored in the same table.

> Over time it could be a lot.

This statement needs to be quantified. 

Repairs can generate 10k+ segments. In a reaper instance that performs a ten repairs per day (on the upper side, since often we see each segment taking an hour or more) we would see 100k+ segments stored per day. That's 36.5 million segments. In the cassandra storage this is 3.6k partitions, each with 10k+ rows.

This is not in my mind a problem. Even after ten years it's only 36k partitions. We're not talking about many MBs/GBs on disk either.

> TTL on repair runs…

Specific TTL at "delete" time i don't think are feasible here, as we need to TTL whole partitions, not just rows, and somehow catch those late coming zombie rows.

TTL at the table level would be a good idea though. Every row written to the `repair_run` table, regardless of its state, gets a TTL of one year.

> Keeping an ever growing repair history is useless, 

I would disagree with this. I would think that accountability is very valuable for operations.

> make listing the repairs very long over time

Nowhere afaik is there a full-table scan on `repair_run` table.

Such queries are always done through either `repair_run_by_cluster` or `repair_run_by_unit`. 
In these two tables of course we would actually delete the IDs.


> will clutter the UI

No it won't, because the UI depends first on queries against `repair_run_by_cluster` or `repair_run_by_unit`. 

(Although later in time, we could add a separate UI page for "history" which would give operators that valuable accountability.)

**Comment by sciclon** [comment]
I agree on having a way to delete repair_runs and avoid increasing the list.
To give you an example I am using the reaper for a cluster with 180 keyspaces, also I am using Datadog with a custom agent which controls the repair window, I mean I defined a maximum of 10 days after the latest repair for each keyspace of each cluster.

The way I use to get the latest success repair is using the DD agent which invokes the spreaper  but I need to get all the repair_runs list which does not escalate as I have to compare and get the latest successfully repair.

The solution should cover all the different storage types as you mentioned. 
So it would be great to limit the history in order to keep growing the list.
I am not an expert in java but I will take a look at the code to see if I can contribute.

**Comment by michaelsembwever** [comment]
@sciclon deleted repair_runs would not show in the UI. See the comment before yours.

> No it won't, because the UI depends first on queries against repair_run_by_cluster or repair_run_by_unit.

That is… we would have to add a UI page to show such past (deleted) history.

**Comment by adejanovski** [comment]
The purge system that was implemented a while ago seems to do its job since we haven't had any report of such issues in the past years.
I'll close this ticket.
