### ISSUE TITLE
Per DC reaper support

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#28]
In a multi dc setup, you should be able to configure a reaper per dc.  This feature would require using Cassandra storage and would involve coordination between DCs.

**Comment by Ritu-Thakur** [comment]
@rustyrazorblade 
When would this feature be available?

**Comment by michaelsembwever** [comment]
@ritu0407 in the next few weeks i'd expect there to be a release.

otherwise feel free to use the `ft-reaper-improvements-final` branch. it's still getting forced push occasionally, but is otherwise stable and ongoing only final polish.
this version of reaper also comes with specific reaper metrics for your monitoring system as well.

**Comment by Ritu-Thakur** [comment]
@michaelsembwever 
Does this developed feature under branch ft-reaper-improvements-final allow multiple instances of reaper per DC or just one instance per DC?

**Comment by michaelsembwever** [comment]
@ritu0407 , multiple per DC.

**Comment by adejanovski** [comment]
The `ft-reaper-improvements-final` branch has now been merged into master, allowing to have one or more Reaper instances per DC.
Closing this issue.
