### ISSUE TITLE
reaper is hang forever

### ISSUE THREAD

**Issue by wavelet123** [thelastpickle/cassandra-reaper#284]
Hi there,

From the reaper log,we can see the following,looks it's hang forever.

reaper-stdout.log.1:INFO   [2017-11-27 11:11:41,521] [da_cas:9d21aa20-d1e3-11e7-adf1-bd0d4c9fe76e] i.c.s.RepairRunner - Next segment to run : 9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e 
reaper-stdout.log.1:INFO   [2017-11-27 11:11:41,998] [da_cas:9d21aa20-d1e3-11e7-adf1-bd0d4c9fe76e:9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e] i.c.s.SegmentRunner - SegmentRunner declined to repair segment 9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e because one of the hosts (172.16.29.62) was already involved in a repair 
reaper-stdout.log.1:INFO   [2017-11-27 11:11:42,475] [da_cas:9d21aa20-d1e3-11e7-adf1-bd0d4c9fe76e:9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e] i.c.s.SegmentRunner - Postponing segment 9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e 
reaper-stdout.log.1:INFO   [2017-11-27 12:28:33,171] [da_cas:9d21aa20-d1e3-11e7-adf1-bd0d4c9fe76e] i.c.s.RepairRunner - Next segment to run : 9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e 
reaper-stdout.log.1:INFO   [2017-11-27 12:28:33,686] [da_cas:9d21aa20-d1e3-11e7-adf1-bd0d4c9fe76e:9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e] i.c.s.SegmentRunner - SegmentRunner declined to repair segment 9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e because one of the hosts (172.16.29.62) was already involved in a repair 
reaper-stdout.log.1:INFO   [2017-11-27 12:28:34,205] [da_cas:9d21aa20-d1e3-11e7-adf1-bd0d4c9fe76e:9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e] i.c.s.SegmentRunner - Postponing segment 9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e 
reaper-stdout.log.1:INFO   [2017-11-27 13:40:37,339] [da_cas:9d21aa20-d1e3-11e7-adf1-bd0d4c9fe76e] i.c.s.RepairRunner - Next segment to run : 9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e 
reaper-stdout.log.1:INFO   [2017-11-27 13:40:37,896] [da_cas:9d21aa20-d1e3-11e7-adf1-bd0d4c9fe76e:9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e] i.c.s.SegmentRunner - It is ok to repair segment '9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e' on repair run with id '9d21aa20-d1e3-11e7-adf1-bd0d4c9fe76e' 
reaper-stdout.log.1:INFO   [2017-11-27 13:40:37,898] [da_cas:9d21aa20-d1e3-11e7-adf1-bd0d4c9fe76e:9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e] i.c.j.JmxProxy - Triggering repair of range (-6488582756894189330,-6486680284699684659] for keyspace "bill" on host 172.16.29.62, with repair parallelism dc_parallel, in cluster with Cassandra version '2.1.18' (can use DATACENTER_AWARE 'true'), for column families: [] 
reaper-stdout.log.1:INFO   [2017-11-27 13:40:37,917] [da_cas:9d21aa20-d1e3-11e7-adf1-bd0d4c9fe76e:9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e] i.c.s.SegmentRunner - Repair for segment 9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e started, status wait will timeout in 900000 millis 
reaper-stdout.log.1:INFO   [2017-11-27 13:40:46,431] [da_cas:9d21aa20-d1e3-11e7-adf1-bd0d4c9fe76e:9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e] i.c.s.SegmentRunner - Repair command 760 on segment 9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e returned with state DONE 

From the UI:

ID | 9d21aa20-d1e3-11e7-adf1-bd0d4c9fe76e
-- | --
Last event | Triggered repair of segment 9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e via host

The progress is not moving any more.

Segment count | 12941

Segment repaired 12228

It's always hang in 12228

Could you please take a look?

Thanks

**Comment by adejanovski** [comment]
Hi, 

Could you please post the settings you've used for that repair ? Do you restrict on specific datacenters ?
Can you check if you have repair related errors in your Cassandra logs ?  
Which version of Cassandra are you using ?

it seems to me like your timeout for repair is a bit low : `900000`
That's 15mn, which is half the default value and could likely lead "big/problematic" segments to be canceled repeatedly by Reaper.
The way Reaper works, if a segment is still running after the timeout, it will be canceled and postponed (retried later). If that happens, there are 2 solutions : 
- expand the timeout
- use a higher number of segments

Having messages such as : `reaper-stdout.log.1:INFO [2017-11-27 12:28:33,686] [da_cas:9d21aa20-d1e3-11e7-adf1-bd0d4c9fe76e:9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e] i.c.s.SegmentRunner - SegmentRunner declined to repair segment 9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e because one of the hosts (172.16.29.62) was already involved in a repair` is expected under normal conditions as Reaper will not allow a node to run 2 repair sessions concurrently.

But as such, your logs don't show something hanging since the last line shows a segment completing correctly : `Repair command 760 on segment 9d263e64-d1e3-11e7-adf1-bd0d4c9fe76e returned with state DONE`

If the repair hangs at the approximate same point each time, I'd say you have some ranges that are more dense than others and probably don't fit within the timeout, or that some nodes have stuck repairs.
You should first move the hanging repair timeout back to 30mn and resume repair. Then, if that still doesn't work, I'd break the repair run into smaller segments.
If progress seems to hang, please run `nodetool tpstats` on all nodes to check if one of them reports a repair as currently running (Look for `AntiEntropySessions` or `Repair#...` depending on your version). You may have a stuck repair on some nodes that will require them to be restarted.

Thanks

**Comment by wavelet123** [comment]
Thanks Alex,I will change it back to 30 minutes,and it's magically successful after restart reaper.

**Comment by adejanovski** [comment]
Cool, I'm very happy to hear this.
