### ISSUE TITLE
Ability to list segments

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#299]
Reaper doesn't currently allow to track segments, just the overall progress.
It would be good to have the ability to display all segments for a specific repair, and now how many segments are currently being processed for each run.

**Comment by Bj0rnen** [comment]
Maybe a bigger change but it would probably be even nicer to have a per-thread "last event", rather than the single one which just happens to display whatever the last thread did (which is often "Postponed due to..."). That would tell you at a glance how many segments are being processed currently. And overall what is going on.

**Comment by adejanovski** [comment]
@Bj0rnen : yeah I've been wanting to change that "last event" thing for a while. 
I was thinking of storing a history of events (either for each repair or for each segment) maybe so it's easier to track what's going on.

Still I think the number of running segments should be based on what's in the segment table. Especially considering that we can have multiple reapers working concurrently when using Cassandra backend.
