### ISSUE TITLE
Repair very slow when trying to repair continously updated table

### ISSUE THREAD

**Issue by gfediere** [thelastpickle/cassandra-reaper#360]
Repear version: _1.1.0_

Hi,

Don't know if this is a real issue, or just a question. But we are trying to repair a table with some columns continuously updated and it takes  along time. We have on logs many entries like:

```
SERVER Mar 05 00:55:59 cstars08e12-par cassandra[17095]: INFO  [RepairJobTask:7] 2018-03-05 00:55:59,039 SyncTask.java:73 - [repair #aa8d5ef0-200f-11e8-b643-1bed0b3d4001] Endpoints /10.20.x and /10.236.x have 7 range(s) out of sync for KEYSPACE_X
SERVER Mar 05 01:19:52 cstars08e12-par cassandra[17095]: INFO  [RepairJobTask:1] 2018-03-05 01:19:52,823 SyncTask.java:73 - [repair #07b9ba80-2013-11e8-b643-1bed0b3d4001] Endpoints /10.20.x and /10.236.x have 100 range(s) out of sync for KEYSPACE_X
SERVER Mar 04 16:29:34 cstars08e16-par cassandra[13624]: INFO  [RepairJobTask:5] 2018-03-04 16:29:34,038 SyncTask.java:73 - [repair #f1b1ed10-1fc8-11e8-8c71-cf8ddd95ae8c] Endpoints /10.20.x and /10.236.x have 129 range(s) out of sync for KEYSPACE_X
```

and reaper interface return:_Postponed due to pending compactions (XX)_
Don't know if this is related to the behavior of the keyspace (continously updated), or because this is the first repair we made and many segments are impacted ?

Thx for your help

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-345) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-345

**Comment by adejanovski** [comment]
Hi, 

which kind of repair are you running ? Full or incremental ?
You apparently have some entropy because it is your first repair and that involves a lot of streaming.
If you have LCS/DTCS tables and use a lot of vnodes, Cassandra is likely to stream a lot of small sstables which will create a lot of pending compactions.
Reaper will then apply backpressure and wait for compactions to catch up before moving on with other segments to prevent putting the cluster through serious performance issues.

I recommend patience, in the hope that you'll have less entropy in the next run and can then enjoy a much faster repair.

Unless you're using LCS and incremental repair, I don't see the continuous updates as the source for this behavior.

**Comment by gfediere** [comment]
Hi @adejanovski ,
Thx for your quick answer, we are doing a full repair and use TWCS as compaction strategy

**Comment by adejanovski** [comment]
Closing this ticket due to inactivity.
