### ISSUE TITLE
LDAP Authentication through docker container

### ISSUE THREAD

**Issue by mrwulf** [thelastpickle/cassandra-reaper#393]
Documentation and an example for the shiro implementation would be great! Especially some guidance toward AD/ldap authentication.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-350) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-350

**Comment by adejanovski** [comment]
I agree, but this is Shiro specific and I have honestly no knowledge of how to configure LDAP auth.
But right now you're right that we're missing proper documentation for auth using Docker containers.

I'll try to update the docs soon.

**Comment by bamartos** [comment]
Hi,

Regarding your question mrwulf I got some help from here: https://github.com/jhegg/shiro-ad-ssl-example

Now, I am not gonna open a new issue since this title can serve my request. Checking the Docker variables session I cant find any variable related with shiro & initConfigs variables. 

Is there a way to use an enviromental variable or I need to provide my own cassandra-reaper.yaml file?

Cheers,

Vasilis

**Comment by ConscriptMR** [comment]
Hey im experiencing trouble with it right now as well, any variables i can change to configure this? or do i need to create a new custom image? also creating a custom image is not very simple and better docs for this would be great

**Comment by adejanovski** [comment]
Shiro authentication setup info is available here: http://cassandra-reaper.io/docs/configuration/authentication/ and shiro ini file can be mounted in the containers and set through the `REAPER_SHIRO_INI` env variable: https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/docker/Dockerfile#L77

I would love better docs, and we happily accept PRs :)
