### ISSUE TITLE
Optimize repair runs scans with the Cassandra backend

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#435]
Let's list all places where we perform repair run scans in Reaper and see what's the best way to optimize the reads.

The plan is to avoid performing full scans when we can avoid them.

**Comment by amorton** [comment]
grooming: needs further definition of "optimise"

**Comment by michaelsembwever** [comment]
From https://github.com/thelastpickle/cassandra-reaper/pull/427#issuecomment-393712932

enrich the `repair_run_by_cluster` table so that initial fetch of the repair run IDs can be filtered better… (it is after all a bit crazy that we have no notion of distinguishing between current and archived repair runs in the C* backend). For example:
```
CREATE TABLE IF NOT EXISTS repair_run_by_cluster (
  cluster_name text,
  repair_run_state text,
  id           timeuuid,
  PRIMARY KEY(cluster_name, repair_run_state, id)
)
```
(and something similar for `repair_run_by_unit`).

It's not that I'm against the idea of the purge feature, but I am conscious about the practicality of it and the (small) cognitive load it does add to the user and the developer. And above all else would like to see the discussion around this stuff land 'on paper'.

**Comment by michaelsembwever** [comment]
Closing, as #437 is waiting on review now.
