### ISSUE TITLE
Reaper not starting after enabling UI Authentication

### ISSUE THREAD

**Issue by kptnew3** [thelastpickle/cassandra-reaper#438]
**Spotted on 1.1.0 (03ce27f)**
Hi,

I enabled the Shiro UI authentication as described in the documentation on cassandra-reaper.io, however after that I restarted the service but reaper didn't start and UI stopped showing up. 

Here are the settings:

## cassandra-reaper.yaml:
accessControl:
  sessionTimeout: PT10M
  shiro:

## /etc/cassandra-reaper/shiro.ini
[main]
authc = org.apache.shiro.web.filter.authc.PassThruAuthenticationFilter
authc.loginUrl = /webui/login.html

[users]
reaper= reaper

[urls]

# Allow anonynous access to login page (and dependencies), but no other pages
/webui/ = authc
/webui = authc
/webui/login.html = anon
/webui/_.html_ = authc
/webui/_.js_ = anon
/ping = anon
/login = anon
/** = anon

Can you let me know if there is anything additional required. 

Regards,
Gagan

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-353) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-353

**Comment by shawnbutts** [comment]
As far as I can tell, this is caused by the same "bug" as https://github.com/thelastpickle/cassandra-reaper/issues/407.

It's in the docs as being in 1.1. But, is not actually  in 1.1 and only available on master.

Since I have also wasted a bit of my time trying to troubleshoot this same issue, perhaps someone with the power could take time to update the official docs([cassandra-reaper.io/](http://cassandra-reaper.io/))to match reality of 1.1 or release 1.1++ to make reality match the docs.

**Comment by kptnew3** [comment]
Thanks a lot Shawn for your time in answering the query. This saved me lot
of time by avoiding to try further experiments.

I would check beta version 1.2 if that works and would post my updates.

Thanks again!
Gagan
