### ISSUE TITLE
Data center names don't align

### ISSUE THREAD

**Issue by pdehlke** [thelastpickle/cassandra-reaper#483]
**Spotted on 1.3.0-SNAPSHOT (03918d5)**

Sadly, I know nothing about UI development, but: 

I have cassandra clusters running in multiple AWS regions. In each region, there is a 'seeds' data center, and a 'data' data center. Data center names reflect the region they're in, for example: us-west-2 and us-west-2-seeds. In this configuration, the summary page at /webui/index.html?currentCluster=all ends up looking like this:
![screen shot 2018-07-13 at 1 47 16 pm](https://user-images.githubusercontent.com/574834/42713306-df315a3a-86a3-11e8-8a6f-783569a38f03.png)

Any way to get those to align properly?

Thank you!

**Comment by adejanovski** [comment]
@pdehlke, 

The problem lies in the difference of data on disk between your datacenters. Reaper helps detecting load imbalances by sizing each node based on the size of data it contains compared to the other nodes. If the imbalance is too heavy, you'll get that kind of "broken" display.
It looks like you're using coordinator nodes of some kind which are not holding much data, and we currently have no plan to support this kind of setup (at least no better than it is right now).

Feel free to submit a PR if you can come up with a proper way of displaying this.

Thanks !
