### ISSUE TITLE
Upgrade from 1.1.0 to 1.2.1 fails due to "unconfigured table snapshot"

### ISSUE THREAD

**Issue by a1exsh** [thelastpickle/cassandra-reaper#496]
Hi,

Today I've tried to upgrade our reaper from v1.1.0 to 1.2.1.  The new version fails to start with the following last lines in the log:
```
INFO   [2018-07-24 14:23:09,971] [main] o.c.c.m.MigrationRepository - Found 14 migration scripts
INFO   [2018-07-24 14:23:12,728] [main] o.c.c.m.MigrationTask - Migrated keyspace reaper_db to version 14
WARN   [2018-07-24 14:23:12,743] [main] i.c.s.c.Migration014 - altering every table to set `dclocal_read_repair_chance` to zero…
WARN   [2018-07-24 14:23:12,746] [main] i.c.s.c.Migration014 - alter every table to set `dclocal_read_repair_chance` to zero completed.
unconfigured table snapshot
```

I see that `snapshot` table should have been added by https://github.com/thelastpickle/cassandra-reaper/blob/1.2.1/src/server/src/main/resources/db/cassandra/011_snapshots.cql
However, in our schema_migration we already have this:
```
cqlsh> select applied_successful, version, executed_at, script_name from reaper_db.schema_migration ;

 applied_successful | version | executed_at              | script_name
--------------------+---------+--------------------------+--------------------------------------------
               True |       1 | 2018-02-05 11:01:24+0000 |                      001_Initialize_db.cql
               True |       2 | 2018-02-05 11:01:45+0000 |                   002_table_properties.cql
               True |       3 | 2018-02-05 11:02:19+0000 |                    003_switch_to_uuids.cql
               True |       4 | 2018-02-05 11:02:26+0000 |              004_fault_tolerant_reaper.cql
               True |       5 | 2018-02-05 11:02:30+0000 |              005_repair_specific_nodes.cql
               True |       6 | 2018-02-05 11:02:32+0000 |                    006_table_blacklist.cql
               True |       7 | 2018-02-05 11:02:35+0000 |             007_segment_count_per_node.cql
               True |       8 | 2018-02-05 11:02:38+0000 |                008_request_for_metrics.cql
               True |       9 | 2018-02-05 11:02:38+0000 |                       009_remove_nulls.cql
               True |      10 | 2018-02-05 11:02:53+0000 |                   010_table_properties.cql
               True |      11 | 2018-02-05 11:02:53+0000 |                    011_fix_start_times.cql
               True |      12 | 2018-07-24 14:23:11+0000 |                 012_segment_coalescing.cql
               True |      13 | 2018-07-24 14:23:12+0000 |               013_multithreaded_repair.cql
               True |      14 | 2018-07-24 14:23:12+0000 | 014_disable_dclocal_read_repair_chance.cql
```
I'm really not sure where this `011_fix_start_times.cql` migration comes from, but it looks like because of it, the new version skips the migration which would create the `snapshot` table.

I will create the table manually, but just wanted to let you know.

**Comment by michaelsembwever** [comment]
Looking into this now @a1exsh

**Comment by a1exsh** [comment]
Interestingly, on another installation of the same version we didn't have trouble upgrading.  So probably the issue was an artifact of using some version older than 1.1.  Thanks for looking anyway!

**Comment by michaelsembwever** [comment]
> Interestingly, on another installation of the same version we didn't have trouble upgrading. So probably the issue was an artifact of using some version older than 1.1. Thanks for looking anyway!

Yes, i believe the Reaper instance needed to have been running 1.0 (at some point) for the bug to have bitten.

**Comment by craigwarburton** [comment]
Had hit this issue. My database had definitely been running at 1.0 at some point.

cat cassandra-reaper.err

Migration V9_0_0__coalesce_segments.sql failed

SQL State : 42S21
Error Code : 42121
Message : Duplicate column name "TOKEN_RANGES"; SQL statement:
ALTER TABLE repair_segment
ADD token_ranges VARCHAR [42121-197]
Location : db/h2/V9_0_0coalesce_segments.sql (/env/reaper/logs/file:/usr/share/cassandra-reaper/cassandra-reaper-1.2.2.jar!/db/h2/V9_0_0coalesce_segments.sql)
Line : 5
Statement : ALTER TABLE repair_segment
ADD token_ranges VARCHAR

cat cassandra-reaper.log

Looking for reaper in /usr/share/cassandra-reaper/
WARN [2018-07-25 23:02:07,833] [main] o.f.c.i.s.JdbcTableSchemaHistory - Could not find schema history table "PUBLIC"."flyway_schema_history", but found "PUBLIC"."schema_version" instead. You are seeing this message because Flyway changed its default for flyway.table in version 5.0.0 to flyway_schema_history and you are still relying on the old default (schema_version). Set flyway.table=schema_version in your configuration to fix this. This fallback mechanism will be removed in Flyway 6.0.0.
WARN [2018-07-25 23:02:08,025] [main] o.f.c.i.s.JdbcTableSchemaHistory - Could not find schema history table "PUBLIC"."flyway_schema_history", but found "PUBLIC"."schema_version" instead. You are seeing this message because Flyway changed its default for flyway.table in version 5.0.0 to flyway_schema_history and you are still relying on the old default (schema_version). Set flyway.table=schema_version in your configuration to fix this. This fallback mechanism will be removed in Flyway 6.0.0.
ERROR [2018-07-25 23:02:08,115] [main] o.f.c.i.c.DbMigrate - Migration of schema "PUBLIC" to version 9.0.0 - coalesce segments failed! Please restore backups and roll back database and code!

**Comment by michaelsembwever** [comment]
@craigwarburton's issue has also been fixed.
