### ISSUE TITLE
"Run now" changes schedule

### ISSUE THREAD

**Issue by ludekdolejsky** [thelastpickle/cassandra-reaper#502]
Hi,

using Reaper 1.2.1 and noticed that if I run a repair via the "Schedules / <Schedule> / Run Now" button, it changes the "Next run" to the time of repair's finish + its interval, e.g. 7 days from now, even if it was originally scheduled to run in e.g. 5 days.

Is this a bug or intended behaviour? 

To me, it would make much more sense if "Run Now" was a one-off repair, but kept the original schedule intact?

Cheers,
Ludek

**Comment by adejanovski** [comment]
Hi @ludekdolejsky,

we were aware of the behavior change when the PR was merged and agreed it was not ideal but not a deal breaker.
Forcing a schedule to run before its planned execution time could be considered as changing the start time and keeping the same interval, otherwise we would be running a repair that is detached from the schedule (which is kind of another feature), not "running the schedule now".

I'll close this ticket but feel free to contribute a PR with your ideal view of that feature.
