### ISSUE TITLE
Schedule "Run now" button does not start a repair

### ISSUE THREAD

**Issue by mharvan** [thelastpickle/cassandra-reaper#506]
In Schedules overview, clicking on the button "Run now" does not do anything.
Expected behavior: A repair for the schedule should be started.

Reaper version 1.2.2
Cassandra version 3.0.16

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-362) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-362

**Comment by adejanovski** [comment]
Hi @mharvan,

the "Run now" button will change the next activation time to the current one and the scheduler should pick up quickly and create the repair run.
Let us know if it's not the case (the next activation time doesn't change).

**Comment by mharvan** [comment]
After clicking "Run now", Next run remains in 4 days.

![image](https://user-images.githubusercontent.com/16802400/43641934-c1fd2f88-9725-11e8-9cac-fed9b1947150.png)

**Comment by adejanovski** [comment]
@mharvan, I can't reproduce the issue, could you check : 

- the javascript console for any error that pops out
- the Reaper logs for errors that would trigger when you press the button

Thanks

**Comment by mharvan** [comment]
There is an error in javascript console (firefox):
![image](https://user-images.githubusercontent.com/16802400/44027472-e38eaac2-9ef6-11e8-9cbd-bc30c0074b39.png)
Reaper logs do not show any new content after I press the button "Run now".

**Comment by mharvan** [comment]
In Chrome, Version 68.0.3440.84 (Official Build) (64-bit), on Ubuntu 18.04 the button "Run now" works as expected.

The javascript console in chrome shows some other errors though. I am not sure whether these errors are relevant:
![image](https://user-images.githubusercontent.com/16802400/44027646-8b51fca0-9ef7-11e8-9f84-616ccbc4a683.png)

**Comment by floco06** [comment]
Ok, managed to find the code in :+1: 
You just need to use the repair_schedule/start/ and then the ID of the schedule
Example : 
curl http://localhost:9500/repair_schedule/st rt/9a10-ed8a-11e8-af5a-332b4e43c049

:+1:

**Comment by eriksw** [comment]
@adejanovski This design of "Run Now" probably needs to be revisited to some degree, because it means that "Run Now" is _completely useless_ when a schedule is disabled—the "Next Run" is updated but it doesn't get run.

(Alternative but disappointing fix for the disabled schedule case would be to disable the "Run Now" command in that state.)

Use case for needing to "Run Now" a disabled schedule:
• I've got a complicated set of repairs (lots of specific sets of tables, set up by hand for want of table-size-aware segmentation)
• I've temporarily disabled the schedules on a cluster while doing a DC cut-over.
• I need to do a full repair using reaper before decommissioning the old DC.
• I need to use the sets of tables I've already set up in the form of schedules, because a naive all-tables repair would never complete in a reasonable amount of time.

I'm using Reaper 2.1.3.
