### ISSUE TITLE
Reaper upgrade failing from 1.2.1 to 1.2.2

### ISSUE THREAD

**Issue by sandeepmallik** [thelastpickle/cassandra-reaper#513]
Hi,

We upgraded reaper from 1.2.1 to 1.2.2. Post upgrade, reaper is not starting. It seems 1.2.2 is trying run alter on below table and failing as column already exists.

Uninstalled 1.2.2 and re-installed it again. Alter table error is gone but reaper is not starting.

Is it something to do with schema disagreement issue like below?

https://github.com/thelastpickle/cassandra-reaper/commit/9c260588d2c9cb193e5e42b63580fc2359fa38e1

Note:- Our cluster has only one node. Cassandra version is 3.11.2.

## Upgrade error.

cat cassandra-reaper.err
Error during migration of script 015_multithreaded_repair.cql while executing 'ALTER TABLE repair_unit_v1 ADD repair_thread_count int;'

root@cqlsh:reaper_db> desc table repair_unit_v1;

CREATE TABLE reaper_db.repair_unit_v1 (
    id timeuuid PRIMARY KEY,
    blacklisted_tables set<text>,
    cluster_name text,
    column_families set<text>,
    datacenters set<text>,
    incremental_repair boolean,
    keyspace_name text,
    nodes set<text>,
    repair_thread_count int
)

## reaper.log

INFO   [main] i.c.ReaperApplication - initializing runner thread pool with 15 threads
INFO   [main] i.c.ReaperApplication - initializing storage of type: cassandra
WARN   [main] i.c.s.CassandraStorage - Customization of cassandra's queryOptions is not supported and will be overridden
INFO   [main] c.d.d.core - DataStax Java driver 3.5.0 for Apache Cassandra
INFO   [main] c.d.d.c.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer
INFO   [main] c.d.d.c.ClockFactory - Using native clock to generate timestamps.
INFO   [main] c.d.d.c.NettyUtil - Found Netty's native epoll transport in the classpath, using it
INFO   [main] c.d.d.c.p.DCAwareRoundRobinPolicy - Using data-center name 'test' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
INFO   [main] c.d.d.c.Cluster - New Cassandra host /127.0.0.1:9042 added
**INFO   [main] o.c.c.m.MigrationRepository - Found 16 migration scripts**

**Comment by michaelsembwever** [comment]
The migration scripts were broken in 1.2.0 and 1.2.1.
That's why they no longer appear public.

Unfortunately you must wipe the reaper_db keyspace and install 1.2.2 fresh.

We are working on integration tests to ensure this does not happen again.

It would be possible to hack/code the migration scripts to make them work, against the current db state you've been left in. But I doubt it's worth the effort.

**Comment by adejanovski** [comment]
Hi @sandeepmallik,

we indeed have an issue with upgrades from 1.2.0/1.2.1 to 1.2.2 because the migration version numbers have been changed.

A quick fix to allow the upgrade to be performed, is to run the following query : 

```
ALTER TABLE reaper_db.repair_unit_v1 DROP repair_thread_count;
```

Then restart Reaper 1.2.2 and the upgrade should go through.
Note that if you had previously created schedules with a repair threads value different than 1, it will be brought back to 0 (which will internally default to 1).
You'll then have to re-create those schedules or update the db directly (the `repair_unit_v1` table).

Very sorry for that inconvenience.

**Comment by sandeepmallik** [comment]
@adejanovski Thanks. Will try this and let you know.

**Comment by adejanovski** [comment]
Ok, that schema disagreement issue is a nasty one and it was introduced in 1.2.0 but fixed in 1.2.1.
If you run into it, the only choice is to drop the reaper_db keyspace indeed.

You can dump your `repair_unit_v1` and `repair_schedule_v1` tables if you want to load them back once the keyspace was recreated from scratch and Reaper started. This will recreate your schedules directly.

I urge you not to restart nodes in the cluster before you've dropped the `reaper_db` keyspace. This bug (which affects Cassandra 3.0/3.x) prevents nodes from restarting.

**Comment by sandeepmallik** [comment]
@adejanovski Thanks. Our cluster is single node and it holds only reaper_db.

**Comment by sandeepmallik** [comment]
Installed 1.2.2. Closing issue.
