### ISSUE TITLE
cassandra repair failed

### ISSUE THREAD

**Issue by aricy** [thelastpickle/cassandra-reaper#565]
hi,
   we use cassandra-reaper tool to repair our big cluster. 
Cluster information: 
size:one big table 4TiB
CompactionPolicy:TWCS
Replica:3
Nodes:3
Disk Partition: JBOD
![image](https://user-images.githubusercontent.com/10055186/46126429-d1107b00-c25f-11e8-9773-188c45e4d65e.png)
we try clean on jbod directory, use repair to recover data(replica), but not work well.
![image](https://user-images.githubusercontent.com/10055186/46126552-585dee80-c260-11e8-934e-b7507cf9a4d0.png)

Can you help me solve the problem.
Thanks.

**Comment by adejanovski** [comment]
Hi @aricy,

your cluster only has 3 nodes and RF=3, so only one segment can be processed at a time.
If you see a running segment when clicking on "View segments" then you just have to be patient.
I think that repairing a 4TB table in just 55 segments could be challenging as you could generate a lot of overstreaming and it will probably take more than 30 minutes per segment, which will result in Reaper forcefully canceling the segment to retry it later.
For such a big table with few nodes, I'd start with 150 segments per node and decrease only if it's really fast to get each segment done. Try to get each segment processed in 1 to 15 minutes if possible. 
You can also raise the timeout in configuration if you still want to process big segments, but I would keep it as a last resort measure.

**Comment by aricy** [comment]
i tuned the configure file:
segmentCountPerNode: 256 [old: 16]
repairParallelism: PARALLEL
repairIntensity: 0.9
scheduleDaysBetween: 7
repairRunThreadCount: 15
hangingRepairTimeoutMins: 3600 [old: 60]
storageType: cassandra
enableCrossOrigin: true
incrementalRepair: false
enableDynamicSeedList: true
repairManagerSchedulingIntervalSeconds: 10
activateQueryLogger: false
jmxConnectionTimeoutInSeconds: 5
useAddressTranslator: false
maxPendingCompactions: 100
Do i need to tune parameter in my case ?

**Comment by adejanovski** [comment]
The segment count can be specified for each repair. The default should stay at 16 in configuration IMO. You may have to repair smaller tables that would benefit from having a small number of segments). Your `hangingRepairTimeoutMins` will make each segment last at most 60 hours, which is fairly big. You should reduce this to no more than a few hours, otherwise you'll leave the possibility of hanging repairs.
You should set the `repairManagerSchedulingIntervalSeconds` to 30 seconds because since your segments are pretty big, it'll just overconsume resources with 10 seconds.

**Comment by aricy** [comment]
ok,thanks , i will try again.

**Comment by adejanovski** [comment]
@aricy , any progress with your repair?

Let us know if we can close this ticket.
