### ISSUE TITLE
Repair runs on incorrect ranges?

### ISSUE THREAD

**Issue by Lyky35** [thelastpickle/cassandra-reaper#712]
Hi I have been running reaper for a while now, with cassandra 2.2.7, and i've noticed that repairs that are being scheduled are done for incorrect ranges or ranges that overlap with other keyspaces.

we can take a basic tables like "system_auth" or/and "system_distributed"

by clicking view segments I see start token and end token. I assume this is the range it repairs?
for example i see this exact same range on both of them (system_auth and system_distributed).
4822554732044444000	4828364812482811000

and when i run this token range manually I find out that it belongs to multiple keyspaces, not only system_* but my other big production tables too. 
Causing the repairs for quite small keyspaces to repair much longer than they need to be.

Let me know if you need any additional info, i'll be more than happy to provide.
Thanks

**Comment by adejanovski** [comment]
Hi @Lyky35,

token ranges are not defined per table in Cassandra. All tables may have partitions for all token ranges in the cluster.
For repairs, each keyspace/table will get repaired on all the token ranges, otherwise it may not be repaired entirely.

Simplifying : Nodes own/replicate token ranges > Tables contain partitions > each partition belongs to one token range.

And tables, whatever their actual size on disk, need to be repaired on all token ranges.
This is why we advise on lowering the number of vnodes in order to lower their overhead on repairs.
Also, using Cassandra 3.0 or later and current versions of Reaper, you'll get token range coalescing in segments, which will group token ranges that have the same replicas in order to make repair faster.
