### ISSUE TITLE
Repair is failing during some AntiEntropy stage

### ISSUE THREAD

**Issue by nezdali** [thelastpickle/cassandra-reaper#755]
Hi, i'm getting an error message on C* node while running repair with reaper 1.4.6, EACH setup in 6 locations, Cassnadra 3.11.4, the repair is almost finished 8107/8158 segments it has been running for 5 days but now it is repairing very slowly, seems that it retries the failed segments all the time and fails during some AntiEntropy stage.

`DEBUG [AntiEntropyStage:1] 2019-09-24 14:16:14,409 RepairMessageVerbHandler.java:131 - Syncing SyncRequest{initiator=/ip1, src=/ip2, dst=-ip3, ranges=[ ranges ]`

`ERROR [AntiEntropyStage:1] 2019-09-24 14:16:15,589 RepairMessageVerbHandler.java:168 - Got error, removing parent repair session 
ERROR [AntiEntropyStage:1] 2019-09-24 14:16:15,590 CassandraDaemon.java:228 - Exception in thread Thread[AntiEntropyStage:1,5,main] java.lang.RuntimeException: Parent repair session with id = e2932a10-ded0-11e9-9635-01198f92da3f has failed.`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-405) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-405

**Comment by adejanovski** [comment]
Hi,

There is a chance that Reaper kills the segment because it lasts more than
3p minutes, which is the default timeout.

How long did the segment last before failing?
What messages do you have in Reaper's logs for this segment?

If it's the case, you'll either need to generate more segments or raise the
timeout.

If it's not what's happening, you should search Cassandra's logs for
messages explaining the failure (on all nodes).

Cheers,

**Comment by nezdali** [comment]
From the reaper log i see that the repair for the failing segment has started:

`INFO   [cluster1:ad9ce3b0-da06-11e9-b3dc-216a39488abf:adbd15e7-da06-11e9-b3dc-216a39488abf] 09:38:24 i.c.s.SegmentRunner - Repair for segment adbd15e7-da06-11e9-b3dc-216a39488abf started, status wait will timeout in 1800000 millis`

and then it exits because of 30 minutes timeout, however the state "NOT_STARTED" is weird.
`DEBUG  [cluster1:ad9ce3b0-da06-11e9-b3dc-216a39488abf:adbd15e7-da06-11e9-b3dc-216a39488abf] 10:08:41 i.c.s.RepairRunner - In repair run #ad9ce3b0-da06-11e9-b3dc-216a39488abf, triggerRepair on segment adbd15e7-da06-11e9-b3dc-216a39488abf ended with state NOT_STARTED`
I will increase the timeout and let you know if it finishes

During the repair process there are a lot of exceptions like this, is it ok ?
`DEBUG  [ForkJoinPool-1-worker-43] 09:38:44 i.c.j.JmxProxy - No repair has run yet on the node. Ignoring exception.javax.management.InstanceNotFoundException:org.apache.cassandra.internal:type=AntiEntropySessions
`

**Comment by adejanovski** [comment]
@nezdali, 

you may be hitting #705. 
What happens is : 
- Reaper creates the segment with the `NOT_STARTED` state
- it triggers the repair on the coordinator node and then waits for a notification from it to move it to `RUNNING`
- The repair session cannot start on the node because of a corrupt SSTable (or another unexpected problem) and the notification is never sent
- The timeout is eventually reached on the Reaper side and the segment gets canceled

You should check the logs on all your Cassandra nodes and look for evidence of the issue there.

>During the repair process there are a lot of exceptions like this, is it ok ?
DEBUG [ForkJoinPool-1-worker-43] 09:38:44 i.c.j.JmxProxy - No repair has run yet on the node. Ignoring exception.javax.management.InstanceNotFoundException:org.apache.cassandra.internal:type=AntiEntropySessions

Yes, that's not a problem and I should really remove this warning as it is confusing.

**Comment by adejanovski** [comment]
@nezdali, did you investigate this further?
Did you manage to fix it?

**Comment by nezdali** [comment]
@adejanovski Have not found anything regarding the corrupted sstables. The plan is to restart these nodes and see any mentioning about corrupted sstables in the logs. If nothing found, i will increase the
segment count as suggested. The cluster is of 48 nodes with 256 vnodes, RF3.  Is it 48*256 to calculate the amount of segments?

**Comment by adejanovski** [comment]
With Cassandra 3.11.x, reaper will group together some token ranges that have the same replicas to reduce the number of segments.
There's no right number of segments, it depends on the amount of data to repair and the entropy of the cluster.
Are you sure there's no error message in the logs in reaper or in Cassandra that could help us understand the issue?

**Comment by nezdali** [comment]
@adejanovski  Cluster is of 48 nodes(8 core/28Gb, 12G for C*) with 256 vnodes, RF3. The keyspace to repair is ~350Gb , the keyspace has 32 tables and 1 materialized_view, estimated partition size for all tables in this keyspace is 927985992. Why the default number of segments is 16 ?
I have not found any obvious errors in C* logs. I'm going to run the repair again.

**Comment by nezdali** [comment]
@adejanovski Repairing majority of the segments finished repairing within 5 days, however few segments out of 8158 took much more time to finish. Repair of those segments got terminated because of timeout, after raising the hangingRepairTimeoutMins from default 60 min to 120min.
Why it took more time to finish these segments with the same Cassandra status?
I have not found anything obvious in the logs. Checked for wide partitions in all the tables  - the max partition is 40mb.

**Comment by adejanovski** [comment]
3.0 brought adaptive repairs which will fix this kind of problem.
@nezdali, I'll close this ticket due to inactivity. Feel free to reopen if needed.
