### ISSUE TITLE
Feature Request: Show total number of compactions pending

### ISSUE THREAD

**Issue by elsmorian** [thelastpickle/cassandra-reaper#877]
Current UI shows the compactions running and their progress, it would be great if it could also show any that are pending - even the number pending similar to that shown in `nodetool compactionstats` would be helpful, but maybe showing them greyed out of with a "yet to start" message in the same table as the current ones running would be nice!

**Comment by rzvoncek** [comment]
I just wanted to to express that we need to wait for the react changes in #895 before moving forward with this.

**Comment by rzvoncek** [comment]
Hi @elsmorian , I've started looking into this. 
The only thing we can do is expose a number of pending compactions, just like we get it from `nodetool compactionstats`. We can't do anything prettier with greyed-out stuff because Cassandra doesn't tell us that. 

So it'll look something like this:
<img width="743" alt="Screenshot 2020-04-30 at 15 29 57" src="https://user-images.githubusercontent.com/2589903/80712540-c2a0da00-8afa-11ea-9a6b-9bc9090b796c.png">

**Comment by elsmorian** [comment]
@rzvoncek Ahh nice - fair enough, even this would be helpful to get an idea of the backlog!
