### ISSUE TITLE
Missing release tgz file in v2.0.4

### ISSUE THREAD

**Issue by chenrui333** [thelastpickle/cassandra-reaper#900]
The release tgz file (`cassandra-reaper-2.0.4.tar.gz` ) is missing in the latest release

**Comment by adejanovski** [comment]
The new GHA based release process is definitely not pushing the built packages the the GH release.
We need to check this

**Comment by ossarga** [comment]
We might be able to test this by forking the repo and debugging the fork.

The Apache Cassandra project has a "dry run" mode for the release that prints the commands that will run to execute the release. We may want to add functionality to the Reaper project this when we fix this issue.

**Comment by ossarga** [comment]
Fixed the issue that was causing this bug on the [2.0](https://github.com/thelastpickle/cassandra-reaper/commit/db593864087a9e6be2e1d0186a97c79c1d4e1a6a) branch. The fix works as the [2.0.5 release build](https://github.com/thelastpickle/cassandra-reaper/actions/runs/140601087) automatically uploaded the binaries to the [GitHub release page](https://github.com/thelastpickle/cassandra-reaper/releases/tag/2.0.5) 

In order to fix the issue with [Release 2.0.4](https://github.com/thelastpickle/cassandra-reaper/releases/tag/2.0.4), I manually attached the binaries that were in Bintray to the release.

**Comment by rzvoncek** [comment]
It looks like this issue is no longer present in a recent build (https://github.com/thelastpickle/cassandra-reaper/actions/runs/140601087). Closing this issue.
